exp_name: SPELL_AS_default
model_name: SPELL
graph_name: ASFORMER_10_10
loss_name: ce_ref
use_spf: False
use_ref: True
w_ref: 5
num_modality: 1
channel1: 64
channel2: 64
final_dim: 19
num_att_heads: 4
dropout: 0.2
lr: 0.0005
wd: 0
batch_size: 1
sch_param: 5
num_epoch: 50
sample_rate: 2
